[Feature/#31] BattleRank 구현
zaranaramorimori/HACKER-ANDROID pull request #32
Opened 2022-03-19 23:20 UTC by kkk5474096

## Related Issues
close #31 

## What Did You Do?
- [x] BattleSeason MockData
- [x] repository pattern
- [x] view

2022-03-20 09:39 UTC, l2hyunwoo requested changes
오 멀티모듈에도 잘 적응한 것 같군요! 추가적으로 고려해볼만한 지점들 코멘트해봤으니 확인해보세요

2022-03-20 09:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +class BattleRankAdapter : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
그냥 리마인드겸 코멘트(지금 수정해야할 부분이 아님)

- 랭크는 페이징 필요해서 추후 PagingDataAdapter로 개편이 요함

2022-03-20 09:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +            }
지난번에 말한 추상클래스로 뷰홀더를 묶으면 코드를 줄일 수 있지 않을까?

2022-03-20 09:39 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +            }
왜 holder의 setIsRecyclable를 false로 두셨나요? 이렇게 사용할 시 리사이클러뷰의 이점을 활용할 수가 없을것 같은데요

2022-03-20 09:39 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseRank.kt
> +
빈줄 삭제!

2022-03-20 09:39 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseRank.kt
> +}
이건 멤버함수로 들어가도 되지않나?

2022-03-20 09:39 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseRank.kt
> +}
이 친구도

2022-03-21 07:52 UTC, kkk5474096 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +            }
맞습니다 수정완료

2022-03-21 07:52 UTC, kkk5474096 commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseRank.kt
> +}
맞습니다~ 반영완료

2022-03-21 07:52 UTC, kkk5474096 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +class BattleRankAdapter : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
페이징으로 결정되면 수정~

2022-03-22 13:17 UTC, l2hyunwoo approved these changes
머지가자고

2022-03-22 13:17 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseRank.kt
> +}
👍🏻

2022-03-22 13:17 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +}
ㅇㅇ 이런 방식으로 설계하는 것을 말했습니당!

2022-03-22 13:19 UTC, kkk5474096 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +}
좋습니다~ 추상 클래스

2022-03-22 13:19 UTC, merged