[Feature/#55] Battle & 닉네임 변경 서버 통신 구현
zaranaramorimori/HACKER-ANDROID pull request #57
Opened 2022-05-24 14:06 UTC by kkk5474096

## Related Issues
- close #55 

## What Did You Do?
- [x] Battle Season 서버 통신 구현
- [x] Battle Rank 서버 통신 구현
- [x] Battle Attack 서버 통신 구현
- [x] 닉네임 변경 서버 통신 구현

2022-05-24 15:27 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/repository/BattleRepositoryImpl.kt
> +
이 부분 삭제 plz

2022-05-24 15:28 UTC, kkk5474096 commented on data/src/main/java/com/teamzzong/hacker/data/repository/BattleRepositoryImpl.kt
> +
이게 있었네

2022-05-25 09:02 UTC, l2hyunwoo approved these changes
OK 머지 가자

2022-05-25 09:02 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/attack/BattleAttackFragment.kt
> +                    }
```suggestion
                    is AttackTeamState.AttackTeam -> teamData(it.team)
```

이런건어떰?

2022-05-25 09:02 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/attack/BattleAttackFragment.kt
> +    private val teamId by intArgs()
@hansh0101 Fragment에서 argument넘길때 우리는 delegate property 사용함

2022-05-25 09:02 UTC, l2hyunwoo commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +        private val itemClick: (Teams) -> (Unit)) :
```suggestion
        private val itemClick: (Teams) -> (Unit)
    ) : CreateRankViewHolder(binding) {
```

괄호 두개 겹쳐있을 땐 하나를 떼는 미덕...

2022-05-25 09:05 UTC, kkk5474096 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/rank/BattleRankAdapter.kt
> +        private val itemClick: (Teams) -> (Unit)) :
제가 정신이 없네요

2022-05-25 09:05 UTC, kkk5474096 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/attack/BattleAttackFragment.kt
> +                    }
해커톤에서 하다보니 코드가 점 그렇네

2022-05-26 11:50 UTC, hansh0101 commented on app/src/main/java/com/teamzzong/hacker/presentation/battle/attack/BattleAttackFragment.kt
> +    private val teamId by intArgs()
확인하였읍니다

2022-05-28 05:52 UTC, l2hyunwoo reviewed
여기까지

2022-05-28 05:52 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/model/response/battle/ResponseBase.kt
> +}
EmptyResponse로 바꿔보는건 어떨까요?

2022-05-28 05:52 UTC, l2hyunwoo commented on data/src/main/java/com/teamzzong/hacker/data/datasource/remote/UserDataSourceImpl.kt
> +    }
이 부분 정도에서 구현 사이즈를 줄여도 될 것 같아. 여기서는 requestDto 대신 string을 써도 무방할듯

2022-05-30 02:40 UTC, l2hyunwoo requested changes
Oh 컨플릭 엄청 많네요....화이링!

2022-06-03 05:25 UTC, l2hyunwoo approved these changes
컨플릭 해결 고생많으셨습니다 👍🏻

2022-06-03 05:25 UTC, merged